# Generated by Django 5.1.4 on 2024-12-18 17:39

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Funcionario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=255)),
                ("email", models.CharField(max_length=255)),
                ("cpf", models.CharField(max_length=50)),
                ("remuneracao", models.DecimalField(decimal_places=2, max_digits=8)),
            ],
            managers=[
                ("objetos", django.db.models.manager.Manager()),
            ],
        ),
    ]
